version: "3.1"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "dockerhost:192.168.15.10"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./etc/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./srv/docker/grafana/data:/var/lib/grafana
    links:
      - prometheus
