version: "3.6"

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=admin123
    volumes:
      - ./config/:/opt/splunk/etc/system/local/
      - ./log/:/var/log/

    ports:
      - 8000:8000
