version: "2.2"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elastic
    environment:
      - node.name=elastic
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.3.2
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elastic
    depends_on:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    networks:
      - elastic
    depends_on:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
