# global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "PromeApp"
    static_configs:
      - targets: ["host.docker.internal:5000"] # the address of an application that exposes metrics for prometheus
    scheme: http
    metrics_path: /metrics-text
