version: "3.1"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./etc/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./srv/docker/grafana/data:/var/lib/grafana
    links:
      - influxdb
    networks:
      logmetric:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    # volumes:
    #   # Data persistency
    #   # sudo mkdir -p /srv/docker/influxdb/data
    #   - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      logmetric:

networks:
  logmetric:
    driver: "bridge"
