version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
  mongo-test:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
